[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
demo_deployment = "RL9Bcs7ypX4ydkBcwL6qMVxLJr5yRdWx3wFCmyCddw8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
